version: '3.1'

services:
  db:
    image: mysql
    volumes: 
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_DATABASE:       mydb
      MYSQL_USER:           user
      MYSQL_PASSWORD:       pass
    ports:
      - 3306:3306
    restart: always

  inventory-service:
    build: .
    links:
      - "db:database"
    ports: 
      - 8080:8080
